name: Deploy Node Application

on: 
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4
      - name: Login to docker hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}     
      - name: Build Docker Image
        run: docker build -t jemmy33/reactjs-app --build-arg REACT_APP_PUBLISH_KEY='${{ secrets.REACT_APP_PUBLISH_KEY }}' --build-arg REACT_APP_API_URL='${{ secrets.REACT_APP_API_URL }}'  .
      - name: Publish Image to docker hub
        run: docker push jemmy33/reactjs-app:latest 

  deploy:
    needs: build
    runs-on: self-hosted 
    steps:
      - name: Pull image from docker hub
        run: docker pull jemmy33/reactjs-app:latest 
      - name: Delete old container
        run: docker rm -f reactjs-app-container || true
      - name: Run Docker Container
        run: docker run -d -p 3000:80 --name reactjs-app-container jemmy33/reactjs-app:latest
